apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-vali-conf
  namespace: fluent-bit
data:
  fluent-bit.conf: |
    [Service]
        Daemon        false
        Http_Listen   0.0.0.0
        Http_Port     2020
        Http_Server   true
        Log_Level     info

    [Input]
        Name          dummy
        Tag           dummy
        Interval_sec  3
        Dummy    {"message":"The log message","namespace_name":"localhost"}
        Metadata {"severity":"INFO","job":"dummy"}

    [Output]
        Name          gardenervali
        Match         dummy
        Labels        {origin="dummy"}
        Url http://vali-0.vali.svc:3100/vali/api/v1/push
        LogLevel debug
        BatchWait 3s
        BatchSize 10240
        LineFormat json
        SortByTimestamp true
        DropSingleKey false
        RemoveKeys stream
        MaxRetries 3
        Timeout 10s
        MinBackoff 15s
        Buffer true
        BufferType dque
        QueueDir  /fluent-bit/buffers
        QueueSync normal
        QueueName dummy
