---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  labels:
    topology.kubernetes.io/zone: "0"
  extraPortMappings:
  - containerPort: 30443
    hostPort: 6443
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        authorization-mode: RBAC,Node
  - |
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    maxPods: 50
    serializeImagePulls: false
    registryPullQPS: 10
    registryBurst: 20

networking:
  ipFamily: ipv4
  podSubnet: 10.0.0.0/24
  serviceSubnet: 10.100.0.0/16
