version: 2
updates:
  # Create PRs for dependency updates
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ":seedling:"
    # Skip gardaner packages. These shall be updated manually.
    ignore:
      - dependency-name: github.com/gardener/*
        versions:
          - "*"
      - dependency-name: github.com/prometheus/*
        versions:
          - "*"
      - dependency-name: github.com/cortexproject/cortex*
        versions:
          - "*"
      - dependency-name: google.golang.org/grpc/*
        versions:
          - "*"
      - dependency-name: k8s.io/*
        versions:
          - "*"
  # Create PRs for golang version updates
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: ":seedling:"
