run:
  concurrency: 4
  deadline: 10m

  skip-files:
  - ".*\\.pb\\.go$"
  - ".*/out_vali\\.go$"
  - ".*/.*_test\\.go$"
  - "tests/.*"
  
linters-settings:
  errcheck:
    exclude: ./exclude_functions.txt
  
linters:
  disable:
  - unused
  enable:
  - revive

issues:
  exclude-use-default: false
  exclude:
  # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  # revive:
  - var-naming # ((var|const|struct field|func) .* should be .*
  - dot-imports # should not use dot imports
  - package-comments # package comment should be of the form
  - unexported-return # exported func .* returns unexported type .*, which can be annoying to use
  - indent-error-flow # if block ends with a return statement, so drop this else and outdent its block
  - "exported: (type|func) name will be used as .* by other packages, and that stutters;"
  # typecheck:
  - "undeclared name: `.*`"
  - "invalid operation: cannot compare .*"
  - "client.StopWait undefined .*"
  - "could not import github.com/gardener/gardener/pkg/apis/core/v1beta1/constants .*"
  - "Error return value of `informer.AddEventHandler` is not checked"
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:" # Excludes messages where deprecated variables are used
  - path: cmd/out_vali\.go
    linters:
    - deadcode