version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  enable: # set of linters in addition to the default set (https://golangci-lint.run/usage/linters/#enabled-by-default)
    - gocritic
    - gosec
    - nlreturn
    - revive
  settings:
    gosec:
      excludes:
        - G115
    revive:
      enable-all-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: dot-imports
          disabled: true
        - name: function-length
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: package-comments
          disabled: true
        - name: use-errors-new
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - path: "pkg/cluster/.*.go$" # exclude controller-gen generated code
        linters:
          - nlreturn
          - revive
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/gardener/logging/v1)
