version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  enable: # set of linters in addition to the default set (https://golangci-lint.run/usage/linters/#enabled-by-default)
    - gocritic
    - gosec
    - nlreturn
    - revive
  settings:
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - path: "pkg/cluster/.*.go$" # exclude controller-gen generated code
        linters:
          - nlreturn
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/gardener/logging)
