run:
  concurrency: 4

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/kit/log.Logger).Log
      - (*github.com/weaveworks/common/logging.Level).Set
      - (*github.com/cortexproject/cortex/pkg/util/flagext.URLValue).Set
  gosec:
    excludes:
      - G115

linters:
  disable:
  - unused
  enable:
  - revive
  - gosec


issues:
  exclude-use-default: false
  exclude:
  # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  # revive:
  - var-naming # ((var|const|struct field|func) .* should be .*
  - dot-imports # should not use dot imports
  - package-comments # package comment should be of the form
  - unexported-return # exported func .* returns unexported type .*, which can be annoying to use
  - indent-error-flow # if block ends with a return statement, so drop this else and outdent its block
  - "exported: (type|func) name will be used as .* by other packages, and that stutters;"
  # typecheck:
  - "undeclared name: `.*`"
  - "invalid operation: cannot compare .*"
  - "client.StopWait undefined .*"
  - "could not import github.com/gardener/gardener/pkg/apis/core/v1beta1/constants .*"
  - "Error return value of `informer.AddEventHandler` is not checked"
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:" # Excludes messages where deprecated variables are used
  - path: cmd/out_vali\.go
    linters:
    - deadcode
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*/out_vali\\.go$"
    - ".*/.*_test\\.go$"
    - "tests/.*"
