version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  enable:
    - gosec
    - revive
  settings:
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: package-comments
          disabled: true
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/gardener/logging)
