version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  enable:
    - gosec
    - revive
  disable:
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/kit/log.Logger).Log
        - (*github.com/weaveworks/common/logging.Level).Set
        - (*github.com/cortexproject/cortex/pkg/util/flagext.URLValue).Set
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - deadcode
        path: cmd/out_vali\.go
      - linters:
          - revive
          - errcheck
        path: tests/*
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/gardener/logging)
