version = 1
SPDX-PackageName = "Gardener logging"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/logging"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["cmd/fluent-bit-output-plugin/output_plugin.go", "pkg/config/config.go", "pkg/config/plugin_config.go",
"pkg/config/client_config.go", "pkg/plugin/vali.go", "pkg/plugin/utils.go", "pkg/client/buffer_client.go",
"pkg/client/dque.go", "pkg/client/buffer.go"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017-2024 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"
