---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit-plugin.plutonoName" . }}-dashboards
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-plugin.plutonoLabels" . | nindent 4 }}
data:
    default.yaml: |-
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: false
        options:
          path: /var/lib/plutono/dashboards
    plutono-fluent-bit-dashboard.json: |-
{{ (.Files.Get "dashboards/plutono-fluent-bit-dashboard.json") | indent 6 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluent-bit-plugin.plutonoName" . }}-datasources
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-plugin.plutonoLabels" . | nindent 4 }}
data:
    datasources.yaml: |-
      datasources:
        # add prometheus datasource
        - name: prometheus
          type: prometheus
          access: proxy
          url: http://logging-prometheus:9090 # prometheus headless service in the same namespace
          isDefault: true
        - name: vali-seed
          type: vali
          access: proxy
          url: http://logging-vali-seed:3100 # vali-seed headless service in the same namespace
          jsonData:
            maxLines: 1000
        - name: vali-shoot
          type: vali
          access: proxy
          url: http://logging-vali-shoot:3100 # vali-shoot headless service in the same namespace
          jsonData:
            maxLines: 1000