---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ include "fluent-bit-plugin.prometheusName" . }}
    namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ include "fluent-bit-plugin.prometheusName" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "fluent-bit-plugin.prometheusName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fluent-bit-plugin.prometheusName" . }}
    namespace: {{ .Release.Namespace }}
