#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname $0)/.."

git config --global user.email "gardener@sap.com"
git config --global user.name "Gardener CI/CD"

apt-get update
apt-get install -y unzip

mkdir -p /go/src/github.com/gardener/logging
cp -r . /go/src/github.com/gardener/logging
cd /go/src/github.com/gardener/logging
